source: source
destination: site
permalink: /news/:year/:month/:day/:title.html
recent_posts: 25       # Posts in the sidebar Recent Posts section
excerpt_link: "More &raquo;"  # "Continue reading" link text at the page bottom
excerpt_separator: "<!-- more -->"
featured_project: Agent-DA7280-FeatherWing
listed_projects: [Agent-MIDI-IN-FeatherWing, Agent-MIDI-OUT-FeatherWing, Agent-DA7280-FeatherWing, Agent-DRV2605-FeatherWing]
name: "PatternAgents"
tagline: "PatternAgents provides community and commerce for electronics designers."
meta:
  robots: "index, follow, noodp, noydir"
  description: "PatternAgents: The Agency of Design Patterns"
  abstract: "PatternAgents provides collaboration, community and commerce for electronics designers."
  classification: "electronics, electronics design, design engineering"
  keywords: "electronics, electronics design, design engineering, open source software, open source hardware, OSHW"
  revisit-after: "7 days"
  rating: "General"

analytics :
  provider : google
  google : 
    tracking_id : 'UA-38592761-1'

comments:
  provider: disqus
  disqus:
    short_name : patternagents

social:
  twitter:
    data-widget-id: 408008079146373120
    data-tweet-limit: 8
    url: https://twitter.com/PatternAgents
    tagline: Tweets by @PatternAgents

store:
  provider: ecwid
  ecwid:
    id: 2101234

baseurl: ""
image_url: /img
video_url: /vid
github_url: https://github.com/PatternAgents

 # ------------------
 # end of _config.yml 
